CS336/CS436: Assignment 2
Assignment 2: Sampling-based Motion Planning
Utils.hpp File Reference
General utilities.
#include <vector>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <sys/time.h>
#include <sys/resource.h>
Defines
#define _USE_MATH_DEFINES
Functions
Geometry
bool IsPointInsidePolygon (const double p[], const int n, const double poly[])
Determine if point p is inside polygon.
static bool IsPointInsidePolygon (const double x, const double y, const int n, const double poly[])
Determine if point (x, y) is inside polygon.
bool SegmentSegmentIntersection (const double p0[], const double p1[], const double p2[], const double p3[])
Return true iff segments <p0, p1> and <p2, p3> intersect.
bool SegmentPolygonIntersection (const double p0[], const double p1[], const int n, const double poly[])
Return true iff segment and polygon intersect.
bool PolygonPolygonCollision (const int n, const double poly[], const int n2, const double poly2[])
Return true iff polygons are in collision.
Pseudorandom Number Generation
static void PseudoRandomSeed (const unsigned int s)
Set the seed for the random number generator.
static unsigned int PseudoRandomSeed (void)
Generate and set the seed for the random number generator.
static double PseudoRandomUniformReal (void)
Generate a real number uniformly at random from the interval [0, 1].
static double PseudoRandomUniformReal (const double min, const double max)
Generate a real number uniformly at random from the interval [min, max].
static long PseudoRandomUniformInteger (const long min, const long max)
Generate an integer number uniformly at random from the interval [min, max].
Timer
typedef struct timeval Clock
static void ClockStart (Clock *const c)
Start the clock.
static double ClockElapsed (Clock *const c)
Measure elapsed time in seconds since clock started.
Detailed Description
General utilities.
Author:
Erion Plaku
Define Documentation
#define _USE_MATH_DEFINES
Typedef Documentation
typedef struct timeval Clock
Function Documentation
bool IsPointInsidePolygon (const double p[], const int n, const double poly[])
Determine if point p is inside polygon.
Parameters:
p 2D point
n number of polygon vertices
poly 2D polygon vertices
Referenced by IsPointInsidePolygon().
static bool IsPointInsidePolygon (const double x, const double y, const int n, const double poly[]) [inline, static]
Determine if point (x, y) is inside polygon.
Parameters:
x x coordinate of 2D point
y y coordinate of 2D point
n number of polygon vertices
poly 2D polygon vertices
References IsPointInsidePolygon().
bool SegmentSegmentIntersection (const double p0[], const double p1[], const double p2[], const double p3[])
Return true iff segments <p0, p1> and <p2, p3> intersect.
Parameters:
p0 2D point
p1 2D point
p2 2D point
p3 2D point
bool SegmentPolygonIntersection (const double p0[], const double p1[], const int n, const double poly[])
Return true iff segment and polygon intersect.
Parameters:
p0 2D point
p1 2D point
n number of polygon vertices
poly 2D polygon vertices
bool PolygonPolygonCollision (const int n, const double poly[], const int n2, const double poly2[])
Return true iff polygons are in collision.
Parameters:
n number of polygon vertices
poly 2D polygon vertices
n2 number of polygon vertices
poly2 2D polygon vertices
static void ClockStart (Clock *const c) [inline, static]
Start the clock.
Parameters:
c pointer to Clock
static double ClockElapsed (Clock *const c) [inline, static]
Measure elapsed time in seconds since clock started.
Parameters:
c pointer to Clock
Description
To measure how much time code is taking do the following: Clock clk; ClockStart(&clk); //code you want to measure const double time = ClockElapsed(&clk); printf("code took %f seconds\n", time);
static void PseudoRandomSeed (const unsigned int s) [inline, static]
Set the seed for the random number generator.
Parameters:
s seed value
Referenced by PseudoRandomSeed().
static unsigned int PseudoRandomSeed (void) [inline, static]
Generate and set the seed for the random number generator.
Returns:
A pseudorandom number read from the file /dev/urandom, which is then used to set the seed using srandom
If file /dev/urandom does not exist, then time(NULL) is used to obtain the seed.
References PseudoRandomSeed().
static double PseudoRandomUniformReal (void) [inline, static]
Generate a real number uniformly at random from the interval [0, 1].
Referenced by PseudoRandomUniformInteger(), and PseudoRandomUniformReal().
static double PseudoRandomUniformReal (const double min, const double max) [inline, static]
Generate a real number uniformly at random from the interval [min, max].
Parameters:
min left boundary of the sampling interval
max right boundary of the sampling interval
References PseudoRandomUniformReal().
static long PseudoRandomUniformInteger (const long min, const long max) [inline, static]
Generate an integer number uniformly at random from the interval [min, max].
Parameters:
min left boundary of the sampling interval
max right boundary of the sampling interval
References PseudoRandomUniformReal().